# 데이터 핸들링 연습문제 3 (배열)

### 1. 1 이상 100 미만의 정수 중 랜덤으로 추출한 50개의 요소를 포함하는 배열 array1을 생성하고 출력하시오. (랜덤 시드는 0으로 고정)

In [14]:
import numpy as np
np.random.seed(0)
array1 = np.random.randint(1,100,50)
array1

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88, 71, 89, 89, 13, 59, 66, 40,
       88, 47, 89, 82, 38, 26, 78, 73, 10, 21, 81, 70, 80, 48, 65, 83, 89,
       50, 30, 20, 20, 15, 40, 33, 66, 10, 58, 33, 32, 75, 24, 36, 76])

### 2. array1의 형태를 5행 10열로 재구조화한 배열 array2를 생성하고 출력하시오.

In [15]:
array2 = array1.reshape(5,10)
array2

array([[45, 48, 65, 68, 68, 10, 84, 22, 37, 88],
       [71, 89, 89, 13, 59, 66, 40, 88, 47, 89],
       [82, 38, 26, 78, 73, 10, 21, 81, 70, 80],
       [48, 65, 83, 89, 50, 30, 20, 20, 15, 40],
       [33, 66, 10, 58, 33, 32, 75, 24, 36, 76]])

### 3. array1의 최댓값과 그 인덱스, 최솟값과 그 인덱스를 출력하시오.

In [16]:
print(array1.max(),array1.argmax(),array1.min(),array1.argmin())

89 11 10 5


### 4. 1 이상 5 이하의 정수를 요소로 갖는 5행 1열의 배열 array3을 생성하고 출력하시오.

In [29]:
np.random.seed(0)
array3 = np.random.randint(1,6,[5,1])
array3.shape 

(5, 1)

### 5. array2에 array3을 열 방향으로 연결한 array4를 생성하고 출력하시오.

In [32]:
array4 = np.hstack((array2,array3))
array4 

### 6. array4에서 값이 20 미만인 요소들의 값과 인덱스와 총 개수를 출력하시오.

In [36]:
vals = array4[array4 < 20]
idxs = np.where(array4 < 20)
nos = len(vals)
print(f'- 20미만인 요소의 값:{vals}\n- 20미만인 요소의 인덱스:{idxs}\n- 총 개수 : {nos}')

- 20미만인 요소의 값:[10  5 13  1 10  4 15  4 10  4]
- 20미만인 요소의 인덱스:(array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int64), array([ 5, 10,  3, 10,  5, 10,  8, 10,  2, 10], dtype=int64))
- 총 개수10


### 7. array4에서 값이 20 미만인 요소들을 1로 변경한 array5를 생성하여 출력하시오.

In [37]:
array5=array4
array5[array4 < 20] = 1
array5

array([[45, 48, 65, 68, 68,  1, 84, 22, 37, 88,  1],
       [71, 89, 89,  1, 59, 66, 40, 88, 47, 89,  1],
       [82, 38, 26, 78, 73,  1, 21, 81, 70, 80,  1],
       [48, 65, 83, 89, 50, 30, 20, 20,  1, 40,  1],
       [33, 66,  1, 58, 33, 32, 75, 24, 36, 76,  1]])

### 8. array5에 로그를 취하고 소숫점 첫째짜리까지 반올림한 배열 array6를 생성하여 출력하시오.

In [39]:
array6 = np.log(array5).round(1)
array6

array([[3.8, 3.9, 4.2, 4.2, 4.2, 0. , 4.4, 3.1, 3.6, 4.5, 0. ],
       [4.3, 4.5, 4.5, 0. , 4.1, 4.2, 3.7, 4.5, 3.9, 4.5, 0. ],
       [4.4, 3.6, 3.3, 4.4, 4.3, 0. , 3. , 4.4, 4.2, 4.4, 0. ],
       [3.9, 4.2, 4.4, 4.5, 3.9, 3.4, 3. , 3. , 0. , 3.7, 0. ],
       [3.5, 4.2, 0. , 4.1, 3.5, 3.5, 4.3, 3.2, 3.6, 4.3, 0. ]])

### 9. array6의 평균, 표준편차, 1사분위수, 3사분위수를 출력하시오.

In [42]:
m,s,qr1,qr3 = array6.mean(),array6.std(),np.quantile(array6,0.25),np.quantile(array6,0.75)
print(f'array6의 평균:{m}\n표준편차:{s}\n1사분위수:{qr1}\n3사분위수:{qr3}')

array6의 평균:3.241818181818182
표준편차:1.5856963952318364
1사분위수:3.1500000000000004
3사분위수:4.3
